name: lint_wf
on:
  workflow_dispatch: 
  pull_request:
    types: 
      - opened
      - reopened
    branches:
      - main

jobs:
  lint_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Lint Code
        id: linter
        uses: astral-sh/ruff-action@v4.0.0            

      - name: Post Comment
        if: failure() && steps.linter.outcome == 'failure'
        uses: KeisukeYamashita/create-comment@v1        
        with:
          comment: |
            ruff check --output-format=full
