name: lint_wf
on:
  workflow_dispatch: 
  pull_request:
    types: 
      - opened
      - reopened
    branches:
      - main

jobs:
  lint_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Lint Code        
        uses: astral-sh/ruff-action@v4.0.0
        with:
          # Arguments passed to Ruff. Use `ruff --help` to see available options. Defaults to `check`.
          args: "--config=ruff.toml"                
